### ISSUE TITLE
footer is missing on nettest pages

### ISSUE THREAD

**Issue by elioqoshi** [TheTorProject/ooni-web#242]
within any of the nettest description pages, the footer is missing:
https://ooni.torproject.org/nettest/

The same footer as on any other page on the website should be incorporated her as well

**Comment by SaptakS** [comment]
I think this is fixed now. Below is a screenshot of the footer in the above mentioned page.
![Screenshot-2019-9-10 OONI - Nettest](https://user-images.githubusercontent.com/9530293/64623714-13967d80-d407-11e9-8246-abb6cecdf063.png)

**Comment by p1g30n** [comment]
The height:100px attribute on the footer seems to prevent the background from covering all of the footer text at views < 700px width. Removing the attribute and adding some bottom-padding on the main container appears like the simplest solution, alternatively some mobile specific css via media query, I will look into a PR

There also seem to be remnants of bootstrap in the code that don't work anymore, there are three pages where bootstrap is inlined[0] but otherwise it appears missing. But that probably deserves its own issue

[0]
https://ooni.torproject.org/notebooks/eg-vs-digitalocean
https://ooni.torproject.org/notebooks/eg-serving-malware
https://ooni.torproject.org/notebooks/internet-blackouts-google-traffic

**Comment by SaptakS** [comment]
Instead of removing the attribute, I think changing `height` to `min-height` is a better solution.

**Comment by p1g30n** [comment]
Agreed. Additionally I would add a `margin-bottom` attribute to the .container class in the 699px media query (line 130 in master.css) to prevent the footer overlapping the content on some mobile views, 50px looks good to me for example

**Comment by SaptakS** [comment]
@p1g30n are you sending a PR? If not, I will love to send a PR.

**Comment by p1g30n** [comment]
@SaptakS Sure, go ahead
